os: linux
dist: trusty
sudo: false
language: minimal

addons:
  apt:
    sources:
      - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main
        key_url: https://packages.microsoft.com/keys/microsoft.asc
    packages:
      - powershell

before_script:
  - pwsh -Command 'Install-Module -Name Pester -Force -Scope CurrentUser'
script:
  - make test

notifications:
  email: false