os: linux
dist: trusty
sudo: required
language: minimal

addons:
  apt:
    sources:
      - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main
        key_url: https://packages.microsoft.com/keys/microsoft.asc
    packages:
      - powershell

before_script:
  - sudo pwsh -Command 'Install-Module -Name Pester -Force'
script:
  - pwsh -Command 'Get-childItem -Recurse *.test.ps1 | foreach { Invoke-Pester $_ }'

notifications:
  email: false